### PR TITLE
Enable parameter support

### PR DESCRIPTION
**Pull request by SamYuan1990**
- update verify scripts.
- update version support for major deps. as kubectl, bcc
- update version support for local-cluster-dev

### CODE REVIEW

**Comment by SamYuan1990** [comment]
as input parameter is a big change, suggestion as tag with 0.0.0 for action and ... after kepler, kepler-operatror, kepler-helm use 0.0.0 merge this PR. and this feature in kepler-action 0.0.1 release. @rootfs , @marceloamaral

**Comment by SamYuan1990** [comment]
@rootfs , by default, I will create a tag with current https://github.com/sustainable-computing-io/kepler-action on Monday night(GMT 8+) 
and create PR in kepler, kepler-helm, kepler-operator.

**Review by rootfs — APPROVED** [review]

**Review by marceloamaral — COMMENTED** [review]
Looks ok to me.

**Comment by SamYuan1990** [comment]
@rootfs , @marceloamaral I suppose as all dependance are updated, we are able to merge this PR.

**Comment by SamYuan1990** [comment]
@sunya-ch it seems you used this action in your own fork. please update accordingly.

**Comment by sunya-ch** [comment]
> @sunya-ch it seems you used this action in your own fork. please update accordingly.

Will this be applied after just rebasing? Do I need to update anything else?

**Pull request merged**
