### PR TITLE
update action

### PR DESCRIPTION
**Pull request by rootfs**
adding `kernel_module_names` input

### CODE REVIEW

**Review by jiere — APPROVED** [review]
LGTM

**Review by vprashar2929 — APPROVED** [review]
LGTM

**Comment by rootfs** [comment]
@jiere @vprashar2929 thanks, can you make a release with this change?

**Comment by vprashar2929** [comment]
@rootfs [v0.0.5](https://github.com/sustainable-computing-io/kepler-action/releases/tag/v0.0.5) is now available.

**Comment by SamYuan1990** [comment]
do we need a default value for `kernel_module_names` to ensure kernel module enabled for kepler?

**Pull request merged**
